# Generated by Django 4.2.4 on 2023-10-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_gender'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlookedat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='account.profile'),
        ),
    ]
