# Generated by Django 4.2.4 on 2023-09-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='type',
            new_name='brand',
        ),
    ]
