# Generated by Django 4.2.4 on 2023-09-13 13:53

import car_collection.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0, validators=[car_collection.core.validators.validate_car_price]),
        ),
    ]
