# Generated by Django 4.2.4 on 2023-09-13 15:22

import car_collection.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default='no image', upload_to='cars/', validators=[car_collection.core.validators.MaxFileSizeInMbValidator(5)]),
            preserve_default=False,
        ),
    ]
