# Generated by Django 4.2.4 on 2023-09-13 14:04

import car_collection.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[car_collection.core.validators.MaxFileSizeInMbValidator(5)]),
        ),
    ]
