# Generated by Django 4.2.4 on 2023-09-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
