# Generated by Django 4.2.4 on 2023-09-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('DoNotShow', 'Do not Show')], default='none', max_length=9),
            preserve_default=False,
        ),
    ]
